name: replace_html_characters
description: With this package, you can easily replace html characters in string data.
version: 1.0.1
homepage: https://github.com/avdisx
repository: https://github.com/avdisx/replace_html_characters
documentation: https://github.com/avdisx/replace_html_characters

environment:
  sdk: '>=3.2.3 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
