name: replace_html_characters
description: With this package, you can easily replace html characters in string data.
version: 1.0.0
homepage: https://github.com/avdisx
repository: https://github.com/avdisx/replace_html_characters
documentation: https://github.com/avdisx/replace_html_characters

environment:
  sdk: ">=2.18.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
